<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e173611a-6b4b-41eb-9b32-5673b41ff084</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middleware\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SeOnePostgresDbContextFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeOne.Application\SeOne.Application.csproj" />
    <ProjectReference Include="..\SeOne.Infrastructure\SeOne.Infrastructure.csproj" />
    <ProjectReference Include="..\SeOne.Migrations.Postgres\SeOne.Migrations.Postgres.csproj" />
  </ItemGroup>

</Project>
